# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test with PyTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-xdist # Testing packages
        pip uninstall textattack --yes # Remove TA if it's already installed 
        python setup.py install_egg_info # Workaround https://github.com/pypa/pip/issues/4537
        pip install -e .[dev]
        pip freeze
    - name: Free disk space
      run: |
        sudo apt-get remove mysql-client libmysqlclient-dev -y >/dev/null 2>&1
        sudo apt-get remove php* -y >/dev/null 2>&1
        sudo apt-get autoremove -y >/dev/null 2>&1
        sudo apt-get autoclean -y >/dev/null 2>&1
        sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
        docker rmi $(docker image ls -aq) >/dev/null 2>&1
        df -h
    - name: Increase swap space
      run: |
        swapon --show
        export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
        sudo swapoff $SWAP_FILE
        sudo dd if=/dev/zero of=$SWAP_FILE bs=1M count=8k oflag=append conv=notrunc # Increase by 8GB
        sudo chmod 0600 $SWAP_FILE
        sudo mkswap $SWAP_FILE
        sudo swapon $SWAP_FILE
        swapon --show
    - name: Test with pytest
      run: |
        echo "skipping tests!"
        # pytest tests -v
        
